
all:

test-scores-1: test-scores-1.c
	gcc test-scores-1.c -o 1

test-scores-2: test-scores-2.c
	gcc test-scores-2.c -o 2

test-scores-3: test-scores-3.c
	gcc test-scores-3.c -o 3

clean:
	rm ./1
	rm ./2
	rm ./3